export const ARTISTS = [
  {
    id: 1,
    name: "Neeti Mohan",
    genre: "Bollywood",
    avatar:
      "https://i.pinimg.com/1200x/d3/71/67/d37167f20fd4520f2aeeadbd368ef656.jpg",
    albums: [
      {
        id: 1,
        title: "Romantic Hits",
        cover:
          "https://i.pinimg.com/1200x/62/08/44/6208448782df0baf176bbf08856f858c.jpg",
        year: 2014,
      },
    ],
  },
  {
    id: 2,
    name: "Shreya Ghoshal",
    genre: "Bollywood",
    avatar:
      "https://i.pinimg.com/736x/83/8a/7a/838a7a9081964a2f633a5491a5b8ae87.jpg",
    albums: [
      {
        id: 2,
        title: "Soulful Melodies",
        cover:
          "https://i.pinimg.com/1200x/ed/dd/96/eddd96276687cf63839c6a5eb0258b95.jpg",
        year: 2014,
      },
    ],
  },
  {
    id: 3,
    name: "Alex Warren",
    genre: "Pop",
    avatar:
      "https://i.pinimg.com/736x/cf/c8/7f/cfc87fad9dcf8d53b610edcd473f56d7.jpg",
    albums: [
      {
        id: 3,
        title: "You'll Be Alright, Kid",
        cover:
          "https://i.pinimg.com/736x/61/f2/1a/61f21a0e99b04c4bd3c5f6ce4918864d.jpg",
        year: 2023,
      },
    ],
  },
  {
    id: 4,
    name: "The 1975",
    genre: "Pop",
    avatar:
      "https://i.pinimg.com/1200x/af/57/e0/af57e0982e423556a51929de514dc55c.jpg",
    albums: [
      {
        id: 4,
        title: "The 1975",
        cover:
          "https://i.pinimg.com/1200x/66/ef/67/66ef67ad3abf6512c8df2a359d775f1b.jpg",
        year: 2022,
      },
    ],
  },
];

export const TRACKS = [
  {
    id: 1,
    title: "Ishq Wala Love",
    artist: "Neeti Mohan",
    genre: "Bollywood",
    albumId: 1,
    cover: "https://i.pinimg.com/1200x/62/08/44/6208448782df0baf176bbf08856f858c.jpg",
    audio: "/ishq-wala-love.mp3",
    lyrics: [
      { time: 0, text: "Surkh wala, souz wala, faiz wala love" },
      { time: 5, text: "Hota hai jo love se zyaada, vaise waalaa love" },
      { time: 10, text: "Ishq waalaa love" },
      { time: 15, text: "Hua jo dard bhee to hamko aaj kuch zyaada hua" },
      { time: 20, text: "Ishq waalaa love" },
      { time: 25, text: "Ye kya hua hai kya khabar yahi pataa hai zyaada hua" },
      { time: 30, text: "Ishq waalaa love" },
      { time: 35, text: "Agar ye usko bhi hua hai, fir bhi mujhko zyada hua" },
      { time: 40, text: "Ishq waalaa love" },
      { time: 45, text: "Meri neend jaise pehlee baar tuuti hai" },
      { time: 50, text: "Ankhe mal ke maine dekhi hai subah" },
      { time: 55, text: "Hui dhoop zyada, leke teri roshani din chada" },
      { time: 60, text: "Ishq waalaa love" },
      { time: 65, text: "Jhaanke baadlon kee jaali ke peechhe se" },
      { time: 70, text: "Kare chandni ye mujhko itla" },
      { time: 75, text: "Leke noor zyaada chaand mera yahin pe hai chhupa" },
      { time: 80, text: "Ishq waalaa love" },
      { time: 95, text: "Kyun na aisa hota, jo milte tum" },
      { time: 100, text: "Ho jaate guum saath mere" },
      { time: 105, text: "Tham ja e tham o dil mere" },
      { time: 110, text: "Toota zyada-zyada tara jab gira" },
      { time: 115, text: "Tab bhi zyaada-zyaada maane naa dil ye sarphira" },
      { time: 120, text: "Ishq waalaa love" },
      { time: 125, text: "Bada ye dil naadan tha, par aaj kuch zyada hua" },
      { time: 130, text: "Jo khone ka tha dar tujhe, pata nahi kyu zyada hua" },
      { time: 145, text: "Surkh wala, souz wala, faiz wala love" },
      { time: 150, text: "Hota hai jo love se zyada vaise vaala love" },
    ],
  },
  {
    id: 2,
    title: "Manwa Laage",
    artist: "Shreya Ghoshal",
    genre: "Bollywood",
    albumId: 2,
    cover:
      "https://i.pinimg.com/1200x/ed/dd/96/eddd96276687cf63839c6a5eb0258b95.jpg",
    audio: "/manwa-laage.mp3",
    lyrics: [
      { time: 0, text: "मनवा लागे, ओ मनवा लागे" },
      { time: 5, text: "लागे रे साँवरे, लागे रे साँवरे" },
      { time: 10, text: "ले तेरा हुआ जिया का, जिया का, ये गाँव रे" },
      { time: 16, text: "मनवा लागे, ओ मनवा लागे" },
      { time: 21, text: "ले खेला मैंने जिया का, जिया का, है दांव रे" },
      { time: 27, text: "मुसाफिर हूँ मैं दूर का, दीवाना हूँ मैं धूप का" },
      { time: 33, text: "मुझे ना भाये, ना भाये, ना भाये छाँव रे" },
      { time: 39, text: "मनवा लागे, ओ मनवा लागे" },
      { time: 50, text: "ऐसी वैसी बोली तेरे नैनों ने बोली" },
      { time: 55, text: "जाने क्यों मैं डोली" },
      { time: 59, text: "बातों की रंगोली से ना खेलूं ऐसे होली मैं" },
      { time: 65, text: "किसी का तो होगा ही तू, क्यूं ना तुझे मैं ही जीतूँ" },
      { time: 71, text: "खुले ख़्वाबों मे जीते हैं, जीते हैं बावरे" },
      { time: 77, text: "मन के धागे, ओ मन के धागे" },
      { time: 82, text: "है लिखा मैंने तेरा ही, तेरा ही तो नाम रे" },
      { time: 90, text: "रस बुँदिया नयन पिया रास रचे" },
      { time: 95, text: "दिल धड़ धड़ धड़के शोर मचे" },
      { time: 100, text: "ऐसे डोरे डाले काला जादू नैना काले" },
      { time: 106, text: "दोनों धीमे धीमे जलें, आजा दोनों ऐसे मिलें" },
      { time: 112, text: "ज़मीं पे लागे, ना तेरे, ना मेरे पाँव रे" },
      { time: 118, text: "मनवा लागे, ओ मनवा लागे" },
      { time: 124, text: "रहूँ मैं तेरे नैनों की, नैनों की ही छाँव रे" },
    ],
  },
  {
    id: 3,
    title: "Carry You Home",
    artist: "Alex Warren",
    genre: "Pop",
    albumId: 3,
    cover:
      "https://i.pinimg.com/736x/61/f2/1a/61f21a0e99b04c4bd3c5f6ce4918864d.jpg",
    audio: "/carry-you-home.mp3",
    lyrics: [
      { time: 0, text: "Oh, I hope you know, I will carry you home" },
      { time: 6, text: "Whether it's tonight or fifty-five years down the road" },
      { time: 12, text: "Oh, I know there's so many ways that this could go" },
      { time: 18, text: "Don't want you to wonder, darling, I need you to know" },
      { time: 24, text: "We were talking to the sunset" },
      { time: 28, text: "Throwing dreams against the wall" },
      { time: 32, text: "I know none of them have stuck yet" },
      { time: 36, text: "But I bet it on you, honey, oh, I would risk it all" },
      { time: 42, text: "These days, these nights are changing" },
      { time: 46, text: "My love, my mind is set on you" },
      { time: 50, text: "I'm not afraid to say it, to say it's true" },
      { time: 55, text: "Oh, I hope you know, I will carry you home" },
      { time: 61, text: "Whether it's tonight or fifty-five years down the road" },
      { time: 72, text: "In this and every life, I choose us every time" },
      { time: 80, text: "We were California dreaming" },
      { time: 84, text: "Our whole life fit in that car" },
      { time: 88, text: "Didn't have a bed to sleep in" },
      { time: 92, text: "We kept each other warm under a ceiling full of stars" },
      { time: 98, text: "These days, these nights are changing" },
      { time: 102, text: "My love, my mind is set on you" },
      { time: 106, text: "I'm not afraid to say it, to say I do" },
      { time: 111, text: "Oh, I hope you know, I will carry you home" },
    ],
  },
  {
    id: 4,
    title: "Ordinary",
    artist: "Alex Warren",
    genre: "Pop",
    albumId: 3,
    cover:
      "https://i.pinimg.com/736x/61/f2/1a/61f21a0e99b04c4bd3c5f6ce4918864d.jpg",
    audio: "/ordinary.mp3",
    lyrics: [
      { time: 0, text: "They say, 'The holy water's watered down'" },
      { time: 5, text: "And this town's lost its faith" },
      { time: 9, text: "Our colors will fade eventually" },
      { time: 13, text: "So, if our time is runnin' out, day after day" },
      { time: 18, text: "We'll make the mundane our masterpiece" },
      { time: 23, text: "Oh my, my — oh my, my love" },
      { time: 28, text: "I take one look at you" },
      { time: 31, text: "You're takin' me out of the ordinary" },
      { time: 36, text: "I want you layin' me down 'til we're dead and buried" },
      { time: 41, text: "I'm on the edge of your knife, stayin' drunk on your vine" },
      { time: 47, text: "The angels up in the clouds are jealous knowin' we found" },
      { time: 53, text: "Somethin' so out of the ordinary" },
      { time: 58, text: "You got me kissin' the ground of your sanctuary" },
      { time: 63, text: "Shatter me with your touch, oh Lord, return me to dust" },
      { time: 70, text: "Hopeless hallelujah, on this side of Heaven's gate" },
      { time: 76, text: "Oh, my life, how do ya breathe and take my breath away?" },
      { time: 82, text: "At your altar, I will pray — you're the sculptor, I'm the clay" },
      { time: 90, text: "World was in black and white until I saw your light" },
      { time: 96, text: "I thought you had to die to find somethin' so out of the ordinary" },
      { time: 104, text: "Somethin' so heavenly, higher than ecstasy" },
      { time: 109, text: "Whenever you're next to me, oh my, my" },
    ],
  },
  {
    id: 5,
    title: "About You",
    artist: "The 1975",
    genre: "Pop",
    albumId: 4,
    cover:
      "https://i.pinimg.com/1200x/66/ef/67/66ef67ad3abf6512c8df2a359d775f1b.jpg",
    audio: "/about-you.mp3",
    lyrics: [
      { time: 0, text: "I know a place, it's somewhere I go" },
      { time: 5, text: "When I need to remember your face" },
      { time: 9, text: "We get married in our heads" },
      { time: 13, text: "Something to do while we try to recall how we met" },
      { time: 19, text: "Do you think I have forgotten?" },
      { time: 23, text: "Do you think I have forgotten about you?" },
      { time: 29, text: "You and I, we're alive, with nothing to do" },
      { time: 34, text: "I could lay and just look in your eyes" },
      { time: 38, text: "Wait and pretend, hold on and hope" },
      { time: 42, text: "That we'll find our way back in the end" },
      { time: 47, text: "Do you think I have forgotten?" },
      { time: 51, text: "Do you think I have forgotten about you?" },
      { time: 60, text: "And there was something 'bout you that now I can't remember" },
      { time: 66, text: "It's the same damn thing that made my heart surrender" },
      { time: 72, text: "And I miss you on a train, I miss you in the morning" },
      { time: 78, text: "I never know what to think about" },
      { time: 82, text: "I think about you" },
      { time: 86, text: "Do you think I have forgotten about you?" },
    ],
  },
];
